name: 🚀 Deploy to cPanel via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Upload to cPanel Server via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy via FTP
        env:
          HOST: ${{ secrets.FTP_HOST }}
          PORT: ${{ secrets.FTP_PORT }}
          USERNAME: ${{ secrets.FTP_USERNAME }}
          PASSWORD: ${{ secrets.FTP_PASSWORD }}
          TARGET: ${{ secrets.FTP_TARGET }}
        run: |
          lftp -u "$USERNAME","$PASSWORD" -p $PORT ftp://$HOST <<EOF
          set ssl:verify-certificate no
          mirror -R ./ $TARGET --delete --verbose
          bye
          EOF
