name: PHPUnit Tests

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.4, 8.0, 8.1 ]

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ccart
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mysqli

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "CACHE_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache Composer Dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-${{ matrix.php-version }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create .env file
        run: |
          cp .env.sample .env
          php -r "file_put_contents('.env', str_replace(
              ['database.tests.hostname = localhost', 'database.tests.database = ccart_test', 'database.tests.username = root', 'database.tests.password = password'],
              ['database.tests.hostname = 127.0.0.1', 'database.tests.database = ccart', 'database.tests.username = root', 'database.tests.password = password'],
              file_get_contents('.env')
          ));"

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit tests/app
